"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Kind = "income" | "expense";
type Status = "paid" | "pending";
type Category = { id: string; name: string; kind: Kind | "both"; color: string };
type Transaction = { id: string; description: string; amount: number; kind: Kind; categoryId: string; date: string; status: Status; recurring: boolean; installmentGroup?: string; installment?: number; installmentTotal?: number };
type Goal = { id: string; name: string; target: number; current: number; icon: string; createdAt: string };
type Event = { id: string; title: string; date: string; amount: number; paid: boolean };
type Settings = { name: string; dark: boolean };
type Store = { version: 1; transactions: Transaction[]; categories: Category[]; goals: Goal[]; pots: Goal[]; events: Event[]; settings: Settings; startedAt: string };
type Modal = null | { type: "transaction"; item?: Transaction } | { type: "goal" | "pot"; item?: Goal } | { type: "category"; item?: Category } | { type: "event"; item?: Event } | { type: "fund"; bucket: "goal" | "pot"; item: Goal };

const KEY = "porquin-finance-v1";
const backupKey = `${KEY}-safety-backup`;
const uid = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const today = () => new Date().toISOString().slice(0, 10);
const monthKey = (date: string) => date.slice(0, 7);
const money = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(n || 0);
const dateLabel = (d: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${d}T12:00:00`));
const defaults: Store = {
  version: 1, transactions: [], goals: [], pots: [], events: [], startedAt: today(), settings: { name: "", dark: true },
  categories: [
    { id: "salary", name: "Salário", kind: "income", color: "#56d68b" }, { id: "extra", name: "Renda extra", kind: "income", color: "#7dd3fc" },
    { id: "food", name: "Alimentação", kind: "expense", color: "#ffad58" }, { id: "home", name: "Moradia", kind: "expense", color: "#f14c8b" },
    { id: "transport", name: "Transporte", kind: "expense", color: "#9b79e8" }, { id: "health", name: "Saúde", kind: "expense", color: "#4fc3c8" },
    { id: "other", name: "Outros", kind: "both", color: "#777582" },
  ],
};

function Pig({ small = false, celebratory = false }: { small?: boolean; celebratory?: boolean }) { return <span className={`pig ${small ? "pig-small" : ""} ${celebratory ? "pig-celebrate" : ""}`} aria-hidden="true"><img src="/porquin-official.png" alt="" /></span>; }
function Empty({ title, text, action, onClick }: { title: string; text: string; action?: string; onClick?: () => void }) { return <div className="empty"><Pig small/><h3>{title}</h3><p>{text}</p>{action && <button className="primary" onClick={onClick}>{action}</button>}</div>; }
function confirmAction(message: string) { return window.confirm(message); }

export default function Home() {
  const [store, setStore] = useState<Store>(defaults);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState("Início");
  const [modal, setModal] = useState<Modal>(null);
  const [toast, setToast] = useState("");
  const [hidden, setHidden] = useState(false);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"all" | Kind | Status>("all");
  const [draftName, setDraftName] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(KEY);
      if (raw) {
        const saved = { ...defaults, ...JSON.parse(raw) } as Store;
        setStore(saved);
        setDraftName(saved.settings.name ?? "");
      }
    } catch {
      localStorage.removeItem(KEY);
    } finally {
      setReady(true);
    }

    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker
          .register("/service-worker.js", { scope: "/" })
          .catch((error) => console.error("Erro ao registrar Service Worker:", error));
      }, { once: true });
    }
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(KEY, JSON.stringify(store)); }, [store, ready]);
  useEffect(() => {
    if (!modal) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = previousOverflow; };
  }, [modal]);
  const update = (fn: (s: Store) => Store, message?: string) => { setStore(fn); if (message) { setToast(message); window.setTimeout(() => setToast(""), 2600); } };
  const category = (id: string) => store.categories.find(c => c.id === id)?.name ?? "Sem categoria";
  const currentMonth = monthKey(today());
  const paid = useMemo(() => store.transactions.filter(t => t.status === "paid"), [store.transactions]);
  const monthTx = useMemo(() => paid.filter(t => monthKey(t.date) === currentMonth), [paid, currentMonth]);
  const totals = useMemo(() => {
    const income = monthTx.filter(t => t.kind === "income").reduce((a, t) => a + t.amount, 0);
    const expense = monthTx.filter(t => t.kind === "expense").reduce((a, t) => a + t.amount, 0);
    const allIncome = paid.filter(t => t.kind === "income").reduce((a, t) => a + t.amount, 0);
    const allExpense = paid.filter(t => t.kind === "expense").reduce((a, t) => a + t.amount, 0);
    const reserved = [...store.goals, ...store.pots].reduce((a, g) => a + g.current, 0);
    return { income, expense, balance: income - expense, patrimony: allIncome - allExpense, reserved };
  }, [monthTx, paid, store.goals, store.pots]);
  const previous = useMemo(() => { const d = new Date(); d.setMonth(d.getMonth() - 1); const key = d.toISOString().slice(0,7); const tx = paid.filter(t => monthKey(t.date) === key); return { income: tx.filter(t=>t.kind==="income").reduce((a,t)=>a+t.amount,0), expense: tx.filter(t=>t.kind==="expense").reduce((a,t)=>a+t.amount,0) }; }, [paid]);
  const categories = useMemo(() => store.categories.map(c => ({ ...c, total: monthTx.filter(t => t.kind === "expense" && t.categoryId === c.id).reduce((a,t)=>a+t.amount,0) })).filter(c=>c.total>0).sort((a,b)=>b.total-a.total), [store.categories, monthTx]);
  const score = useMemo(() => { if (!store.transactions.length) return 0; let v=45; if(totals.balance>0)v+=20; if(totals.income && totals.expense/totals.income<.7)v+=15; if(totals.reserved>0)v+=10; if(!store.transactions.some(t=>t.status==="pending"&&t.date<today()))v+=10; return Math.min(100,v); }, [store.transactions, totals]);
  const insights = useMemo(() => { if (!monthTx.length) return ["Cadastre sua primeira movimentação para receber insights personalizados."]; const out=[] as string[]; if(previous.expense) out.push(`Você gastou ${Math.abs(Math.round((totals.expense/previous.expense-1)*100))}% ${totals.expense<=previous.expense?"menos":"mais"} que no mês anterior.`); if(categories[0]) out.push(`${categories[0].name} é sua maior categoria de gastos neste mês.`); if(totals.balance>0) out.push(`Você economizou ${money(totals.balance)} neste mês. Continue assim!`); if(totals.balance<0) out.push(`Suas despesas superaram as receitas em ${money(Math.abs(totals.balance))}.`); return out.length?out:["Seus dados estão atualizados. Continue registrando suas movimentações."]; }, [monthTx, previous.expense, totals, categories]);
  const achievements = useMemo(() => [{name:"Primeiro passo",ok:store.transactions.length>0},{name:"Primeira meta",ok:store.goals.length>0},{name:"Primeiros R$ 1.000",ok:totals.reserved>=1000},{name:"Mês no positivo",ok:totals.balance>0}], [store.transactions,store.goals,totals]);
  const filtered = useMemo(() => store.transactions.filter(t => (filter==="all" || t.kind===filter || t.status===filter) && `${t.description} ${category(t.categoryId)}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)), [store.transactions, filter, query, store.categories]);

  function saveTransaction(e: React.FormEvent<HTMLFormElement>, item?: Transaction) {
    e.preventDefault(); const f=new FormData(e.currentTarget); const amount=Number(f.get("amount")); const installments=Math.max(1,Number(f.get("installments")||1)); if(!amount || amount<=0)return;
    const base={ description:String(f.get("description")).trim(), amount:Math.round(amount*100)/100, kind:f.get("kind") as Kind, categoryId:String(f.get("categoryId")), date:String(f.get("date")), status:f.get("status") as Status, recurring:f.get("recurring")==="on" };
    update(s=>{ if(item) return {...s,transactions:s.transactions.map(t=>t.id===item.id?{...item,...base}:t)}; if(installments===1)return{...s,transactions:[{...base,id:uid()},...s.transactions]}; const group=uid(); const part=Math.round(amount/installments*100)/100; const made=Array.from({length:installments},(_,i)=>{const d=new Date(`${base.date}T12:00:00`);d.setMonth(d.getMonth()+i);return{...base,id:uid(),amount:i===installments-1?Math.round((amount-part*(installments-1))*100)/100:part,date:d.toISOString().slice(0,10),installmentGroup:group,installment:i+1,installmentTotal:installments};}); return{...s,transactions:[...made,...s.transactions]}; }, item?"Movimentação atualizada":"Movimentação salva"); setModal(null);
  }
  function deleteTx(t:Transaction){if(confirmAction(`Excluir “${t.description}”?`))update(s=>({...s,transactions:s.transactions.filter(x=>x.id!==t.id)}),"Movimentação excluída");}
  function saveGoal(e:React.FormEvent<HTMLFormElement>, bucket:"goal"|"pot", item?:Goal){e.preventDefault();const f=new FormData(e.currentTarget);const next={id:item?.id??uid(),name:String(f.get("name")),target:Number(f.get("target")),current:item?.current??Number(f.get("current")||0),icon:String(f.get("icon")||"🐷"),createdAt:item?.createdAt??today()};const key=bucket==="goal"?"goals":"pots";update(s=>({...s,[key]:item?s[key].map(g=>g.id===item.id?next:g):[...s[key],next]}),item?"Atualizado com sucesso":"Criado com sucesso");setModal(null);}
  function saveFund(e:React.FormEvent<HTMLFormElement>, bucket:"goal"|"pot", item:Goal){e.preventDefault();const f=new FormData(e.currentTarget);const amount=Number(f.get("amount"));const direction=String(f.get("direction"));const key=bucket==="goal"?"goals":"pots";update(s=>({...s,[key]:s[key].map(g=>g.id===item.id?{...g,current:Math.max(0,Math.min(g.target,direction==="add"?g.current+amount:g.current-amount))}:g)}),"Saldo atualizado");setModal(null);}
  function removeGoal(bucket:"goal"|"pot",g:Goal){if(confirmAction(`Excluir “${g.name}”?`)){const key=bucket==="goal"?"goals":"pots";update(s=>({...s,[key]:s[key].filter(x=>x.id!==g.id)}),"Excluído com sucesso");}}
  function saveCategory(e:React.FormEvent<HTMLFormElement>,item?:Category){e.preventDefault();const f=new FormData(e.currentTarget);const c={id:item?.id??uid(),name:String(f.get("name")),kind:f.get("kind") as Category["kind"],color:String(f.get("color"))};update(s=>({...s,categories:item?s.categories.map(x=>x.id===item.id?c:x):[...s.categories,c]}),"Categoria salva");setModal(null);}
  function removeCategory(c:Category){if(store.transactions.some(t=>t.categoryId===c.id)){setToast("Categoria em uso: transfira as movimentações antes de excluir");return;}if(confirmAction(`Excluir categoria “${c.name}”?`))update(s=>({...s,categories:s.categories.filter(x=>x.id!==c.id)}),"Categoria excluída");}
  function saveEvent(e:React.FormEvent<HTMLFormElement>,item?:Event){e.preventDefault();const f=new FormData(e.currentTarget);const v={id:item?.id??uid(),title:String(f.get("title")),date:String(f.get("date")),amount:Number(f.get("amount")||0),paid:item?.paid??false};update(s=>({...s,events:item?s.events.map(x=>x.id===item.id?v:x):[...s.events,v]}),"Evento salvo");setModal(null);}
  function exportData(){const blob=new Blob([JSON.stringify(store,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`porquin-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);setToast("Backup exportado");}
  function importData(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));if(parsed.version!==1||!Array.isArray(parsed.transactions)||!Array.isArray(parsed.categories))throw new Error();localStorage.setItem(backupKey,JSON.stringify(store));setStore({...defaults,...parsed});setToast("Dados importados com segurança");}catch{setToast("Arquivo inválido. Seus dados não foram alterados.");}};reader.readAsText(file);e.target.value="";}
  function clearData(){if(confirmAction("Isso apagará todos os seus dados financeiros. Uma cópia de segurança será criada. Deseja continuar?")){localStorage.setItem(backupKey,JSON.stringify(store));setStore({...defaults,settings:store.settings,startedAt:today()});setToast("Dados limpos. Backup de segurança criado.");}}
  function restoreSafety(){const raw=localStorage.getItem(backupKey);if(!raw){setToast("Nenhum backup de segurança disponível");return;}if(confirmAction("Restaurar o último backup de segurança?")){setStore(JSON.parse(raw));setToast("Backup restaurado");}}
  function go(name:string){setTab(name);window.scrollTo({top:0,behavior:"smooth"});}
  const nav=[["⌂","Início"],["↕","Transações"],["＋","Adicionar"],["◎","Metas"],["◉","Perfil"]];

  if(!ready)return <main className="app dark loading"><Pig/><p>Preparando seu Porquin…</p></main>;
  return <main className={`app ${store.settings.dark?"dark":"light"}`}>
    <div className="ambient one"/><div className="ambient two"/>
    <aside className="sidebar"><div className="brand"><Pig/><div><strong>Porquin</strong><span>Finance</span></div></div><p className="brand-copy">Organize. Economize.<br/>Realize seus sonhos.</p><nav className="side-nav">{[["⌂","Início"],["↕","Transações"],["◎","Metas"],["🐷","Cofrinhos"],["▣","Calendário"],["◉","Perfil"]].map(([i,n])=><button key={n} className={tab===n?"active":""} onClick={()=>go(n)}><b>{i}</b>{n}</button>)}</nav><div className="privacy-card"><span>⌁</span><div><b>100% local</b><small>Seus dados ficam só com você</small></div></div><button className="theme" onClick={()=>update(s=>({...s,settings:{...s.settings,dark:!s.settings.dark}}))}>{store.settings.dark?"☀ Tema claro":"☾ Tema escuro"}</button></aside>
    <section className="content"><header><div className="header-title"><Pig small/><div><span className="eyebrow">{tab.toUpperCase()}</span><h1>{tab==="Início"?`Olá${store.settings.name?`, ${store.settings.name.split(" ")[0]}`:""}! 👋`:tab}</h1><p>{tab==="Início"?"Veja sua vida financeira com clareza.":"Tudo salvo automaticamente neste dispositivo."}</p></div></div><div className="header-actions"><button className="add-top" onClick={()=>setModal({type:"transaction"})}>＋ Nova movimentação</button></div></header>
      {tab==="Início"&&Dashboard()}{tab==="Transações"&&Transactions()}{tab==="Metas"&&Buckets({bucket:"goal"})}{tab==="Cofrinhos"&&Buckets({bucket:"pot"})}{tab==="Calendário"&&Calendar()}{tab==="Perfil"&&Profile()}
    </section>
    <nav className="bottom-nav">{nav.map(([i,n])=><button key={n} className={`${tab===n?"active":""} ${n==="Adicionar"?"add":""}`} onClick={()=>n==="Adicionar"?setModal({type:"transaction"}):go(n)}><b>{i}</b><span>{n}</span></button>)}</nav>
    {modal&&ModalView()}{toast&&<div className="toast">✓ {toast}</div>}
  </main>;

  function Dashboard(){return <><section className="hero-grid"><article className="balance-card"><div className="balance-top"><span>Patrimônio líquido</span><button onClick={()=>setHidden(!hidden)}>{hidden?"⊘":"◉"}</button></div><strong>{hidden?"R$ ••••••":money(totals.patrimony)}</strong><div className="balance-foot"><span>{totals.balance>=0?"↗":"↘"} {money(Math.abs(totals.balance))} no mês</span><Pig small/></div></article><article className="score-card"><div><span>Saúde financeira</span><strong>{score}<small>/100</small></strong><p>{score?score>=80?"Excelente equilíbrio.":score>=60?"Você está evoluindo.":"Há espaço para melhorar.":"Comece adicionando seus dados."}</p></div><div className="score-ring" style={{background:`conic-gradient(#f65390 ${score}%,rgba(255,255,255,.06) 0)`}}><span>{score}</span></div></article></section>
    <section className="stat-grid"><article><div><span className="stat-icon green">↗</span><span>Receitas do mês</span></div><strong>{hidden?"••••":money(totals.income)}</strong><small>{previous.income?`${Math.round((totals.income/previous.income-1)*100)}% vs. mês anterior`:"Sem comparação anterior"}</small></article><article><div><span className="stat-icon pink">↘</span><span>Despesas pagas</span></div><strong>{hidden?"••••":money(totals.expense)}</strong><small>{store.transactions.filter(t=>t.status==="pending").length} pendente(s)</small></article><article><div><span className="stat-icon purple">＝</span><span>Saldo do mês</span></div><strong>{hidden?"••••":money(totals.balance)}</strong><small className={totals.balance>=0?"positive":""}>{totals.balance>=0?"Você está no positivo":"Atenção ao orçamento"}</small></article></section>
    <section className="main-grid"><article className="panel chart-panel"><div className="panel-head"><div><span>EVOLUÇÃO</span><h2>Receitas × despesas</h2></div></div><DynamicChart/></article><article className="panel categories"><div className="panel-head"><div><span>DESPESAS</span><h2>Por categoria</h2></div></div>{categories.length?<div className="category-bars">{categories.map(c=><div key={c.id}><span><b>{c.name}</b><small>{money(c.total)} · {totals.expense?Math.round(c.total/totals.expense*100):0}%</small></span><i><em style={{width:`${totals.expense?c.total/totals.expense*100:0}%`,background:c.color}}/></i></div>)}</div>:<Empty title="Sem despesas neste mês" text="As categorias aparecerão aqui conforme você registrar seus gastos."/>}</article></section>
    <section className="lower-grid"><article className="panel transactions"><div className="panel-head"><div><span>ATIVIDADE</span><h2>Últimas movimentações</h2></div><button onClick={()=>go("Transações")}>Ver todas →</button></div>{store.transactions.length?store.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(TxRow):<Empty title="Sua história começa aqui" text="Adicione a primeira receita ou despesa." action="Adicionar movimentação" onClick={()=>setModal({type:"transaction"})}/>}</article><article className="panel goals"><div className="panel-head"><div><span>PLANOS</span><h2>Metas financeiras</h2></div><button onClick={()=>go("Metas")}>Ver todas →</button></div>{store.goals.length?store.goals.slice(0,3).map(g=><GoalRow key={g.id} g={g}/>):<Empty title="Nenhuma meta criada" text="Transforme seus planos em progresso visível." action="Criar meta" onClick={()=>setModal({type:"goal"})}/>}</article></section>
    <section className="insight"><div className="bulb">✦</div><div><span>INSIGHT DO PORQUIN</span><h3>{insights[0]}</h3><p>{insights[1]??"Este insight muda automaticamente conforme seus registros."}</p></div><Pig/></section></>}
  function DynamicChart(){const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(5-i));const key=d.toISOString().slice(0,7);const tx=paid.filter(t=>monthKey(t.date)===key);return{label:new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(d),income:tx.filter(t=>t.kind==="income").reduce((a,t)=>a+t.amount,0),expense:tx.filter(t=>t.kind==="expense").reduce((a,t)=>a+t.amount,0)}});const max=Math.max(1,...months.flatMap(m=>[m.income,m.expense]));return <div className="bar-chart">{months.map(m=><div className="bar-month" key={m.label}><div className="bars"><i title={`Receitas ${money(m.income)}`} style={{height:`${m.income/max*100}%`}}/><i className="expense" title={`Despesas ${money(m.expense)}`} style={{height:`${m.expense/max*100}%`}}/></div><span>{m.label}</span></div>)}</div>}
  function Transactions(){return <><section className="toolbar"><input placeholder="Pesquisar movimentações…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">Todas</option><option value="income">Receitas</option><option value="expense">Despesas</option><option value="paid">Pagas</option><option value="pending">Pendentes</option></select><button className="secondary" onClick={()=>setModal({type:"category"})}>Categorias</button></section><article className="panel list-panel">{filtered.length?filtered.map(t=><div className="transaction editable" key={t.id}>{TxRow(t)}<div className="row-actions"><button onClick={()=>setModal({type:"transaction",item:t})}>Editar</button><button onClick={()=>deleteTx(t)}>Excluir</button></div></div>):<Empty title="Nenhuma movimentação encontrada" text={query?"Tente mudar sua pesquisa ou filtro.":"Adicione receitas e despesas para começar."} action={!query?"Adicionar agora":undefined} onClick={()=>setModal({type:"transaction"})}/>}</article></>}
  function TxRow(t:Transaction){return <><span className={t.kind}>{t.kind==="income"?"↗":"↘"}</span><div><b>{t.description}</b><small>{category(t.categoryId)} · {dateLabel(t.date)}{t.installment?` · ${t.installment}/${t.installmentTotal}`:""} · {t.status==="paid"?"Pago":"Pendente"}</small></div><strong className={t.kind==="income"?"positive":""}>{t.kind==="income"?"+ ":"− "}{money(t.amount)}</strong></>}
  function Buckets({bucket}:{bucket:"goal"|"pot"}){const list=bucket==="goal"?store.goals:store.pots;return <><div className="section-action"><p>{bucket==="goal"?"Crie objetivos e acompanhe cada conquista.":"Separe seu dinheiro em espaços independentes."}</p><button className="primary" onClick={()=>setModal({type:bucket})}>＋ {bucket==="goal"?"Nova meta":"Novo cofrinho"}</button></div>{list.length?<section className="bucket-grid">{list.map(g=><article className="panel bucket" key={g.id}><GoalRow g={g}/><div className="bucket-actions"><button onClick={()=>setModal({type:"fund",bucket,item:g})}>＋/− Saldo</button><button onClick={()=>setModal({type:bucket,item:g})}>Editar</button><button onClick={()=>removeGoal(bucket,g)}>Excluir</button></div></article>)}</section>:<article className="panel"><Empty title={bucket==="goal"?"Nenhuma meta ainda":"Nenhum cofrinho ainda"} text={bucket==="goal"?"Crie uma meta para acompanhar seu progresso.":"Crie cofrinhos para organizar suas reservas."} action={bucket==="goal"?"Criar primeira meta":"Criar primeiro cofrinho"} onClick={()=>setModal({type:bucket})}/></article>}</>}
  function GoalRow({g}:{g:Goal}){const pct=Math.min(100,Math.round(g.current/g.target*100)||0);return <div className={`goal ${pct>=100?"complete":""}`}><span className="goal-icon">{pct>=100?<Pig small celebratory/>:<span aria-hidden="true">{g.icon||"🐷"}</span>}</span><div><div><b>{g.name}</b><strong>{pct}%</strong></div><small>{money(g.current)} de {money(g.target)}</small><i><em style={{width:`${pct}%`}}/></i>{pct>=100&&<small className="positive">🎉 Parabéns! Objetivo concluído!</small>}</div></div>}
  function Calendar(){const all=[...store.events.map(e=>({...e,type:"event"})),...store.transactions.filter(t=>t.status==="pending").map(t=>({id:t.id,title:t.description,date:t.date,amount:t.amount,paid:false,type:"tx"}))].sort((a,b)=>a.date.localeCompare(b.date));return <><div className="section-action"><p>Eventos e vencimentos pendentes em um só lugar.</p><button className="primary" onClick={()=>setModal({type:"event"})}>＋ Novo evento</button></div><article className="panel calendar-list">{all.length?all.map(e=><div className="calendar-item" key={`${e.type}-${e.id}`}><time><b>{e.date.slice(8,10)}</b><span>{new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(new Date(`${e.date}T12:00:00`))}</span></time><div><b>{e.title}</b><small>{money(e.amount)} · {e.paid?"Pago":"Pendente"}</small></div>{e.type==="event"&&<><button onClick={()=>update(s=>({...s,events:s.events.map(x=>x.id===e.id?{...x,paid:!x.paid}:x)}),"Status atualizado")}>{e.paid?"Reabrir":"Marcar pago"}</button><button onClick={()=>setModal({type:"event",item:store.events.find(x=>x.id===e.id)})}>Editar</button><button onClick={()=>confirmAction("Excluir este evento?")&&update(s=>({...s,events:s.events.filter(x=>x.id!==e.id)}),"Evento excluído")}>Excluir</button></>}</div>):<Empty title="Calendário vazio" text="Eventos e vencimentos pendentes aparecerão aqui." action="Adicionar evento" onClick={()=>setModal({type:"event"})}/>}</article></>}
  function Profile(){return <section className="settings-grid"><article className="panel settings mascot-about"><Pig/><div><span className="eyebrow">MASCOTE OFICIAL</span><h2>Conheça o Porquin 🐷</h2><p>O Porquin é seu companheiro para organizar o dinheiro com leveza, segurança e confiança. Ele aparece apenas nos momentos importantes da sua jornada.</p></div></article><article className="panel settings"><h2>Preferências</h2><label>Seu nome<input type="text" value={draftName} placeholder="Como devemos chamar você?" autoComplete="name" maxLength={60} onChange={e=>setDraftName(e.target.value)} onBlur={()=>{const name=draftName.trim();setDraftName(name);update(s=>({...s,settings:{...s.settings,name}}));}}/></label><button className="secondary" onClick={()=>update(s=>({...s,settings:{...s.settings,dark:!s.settings.dark}}))}>{store.settings.dark?"Ativar tema claro":"Ativar tema escuro"}</button></article><article className="panel settings backup-card"><div className="backup-title"><span className="backup-icon" aria-hidden="true">🔐</span><div><h2>Seus dados</h2><p>Exporte uma cópia, importe um arquivo válido ou restaure o backup de segurança.</p></div></div><div className="settings-actions"><button className="primary" onClick={exportData}>Exportar backup</button><button className="secondary" onClick={()=>fileRef.current?.click()}>Importar dados</button><button className="secondary" onClick={restoreSafety}>Restaurar backup</button><button className="danger" onClick={clearData}>Limpar dados</button></div><input ref={fileRef} hidden type="file" accept="application/json" onChange={importData}/></article><article className="panel settings"><h2>Conquistas</h2>{achievements.map(a=><div className={`achievement ${a.ok?"unlocked":""}`} key={a.name}><span className="achievement-medal" aria-hidden="true">{a.ok?"🏅":"○"}</span><b>{a.name}</b><small>{a.ok?"Desbloqueada":"Ainda bloqueada"}</small></div>)}</article><article className="panel settings"><h2>Categorias</h2>{store.categories.map(c=><div className="category-manage" key={c.id}><i style={{background:c.color}}/><b>{c.name}</b><small>{c.kind==="both"?"Ambos":c.kind==="income"?"Receita":"Despesa"}</small><button onClick={()=>setModal({type:"category",item:c})}>Editar</button><button onClick={()=>removeCategory(c)}>Excluir</button></div>)}<button className="secondary" onClick={()=>setModal({type:"category"})}>＋ Nova categoria</button></article></section>}
  function ModalView(){if(!modal)return null;let body:React.ReactNode;if(modal.type==="transaction"){const t=modal.item;body=<form className="modal" onSubmit={e=>saveTransaction(e,t)}><Close/><span className="eyebrow">MOVIMENTAÇÃO</span><h2>{t?"Editar registro":"Novo registro"}</h2><label>Descrição<input name="description" required defaultValue={t?.description}/></label><div className="form-row"><label>Valor total<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={t?.amount}/></label><label>Tipo<select name="kind" defaultValue={t?.kind??"expense"}><option value="expense">Despesa</option><option value="income">Receita</option></select></label></div><div className="form-row"><label>Data<input name="date" type="date" required defaultValue={t?.date??today()}/></label><label>Status<select name="status" defaultValue={t?.status??"paid"}><option value="paid">Pago/recebido</option><option value="pending">Pendente</option></select></label></div><label>Categoria<select name="categoryId" defaultValue={t?.categoryId??store.categories[0]?.id}>{store.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{!t&&<div className="form-row"><label>Parcelas<input name="installments" type="number" min="1" max="120" defaultValue="1"/></label><label className="check"><input name="recurring" type="checkbox"/> Repetir mensalmente</label></div>}<button className="submit">Salvar movimentação</button></form>}
    else if(modal.type==="goal"||modal.type==="pot"){const g=modal.item;body=<form className="modal" onSubmit={e=>saveGoal(e,modal.type==="goal"?"goal":"pot",g)}><Close/><h2>{g?"Editar":"Criar"} {modal.type==="goal"?"meta":"cofrinho"}</h2><label>Nome<input name="name" required defaultValue={g?.name}/></label><div className="form-row"><label>Valor alvo<input name="target" type="number" min="0.01" step="0.01" required defaultValue={g?.target}/></label><label>Ícone<input name="icon" maxLength={4} defaultValue={g?.icon??"🐷"}/></label></div>{!g&&<label>Valor inicial<input name="current" type="number" min="0" step="0.01" defaultValue="0"/></label>}<button className="submit">Salvar</button></form>}
    else if(modal.type==="fund"){body=<form className="modal" onSubmit={e=>saveFund(e,modal.bucket,modal.item)}><Close/><h2>Atualizar saldo</h2><p>{modal.item.name} · atual {money(modal.item.current)}</p><label>Operação<select name="direction"><option value="add">Adicionar dinheiro</option><option value="remove">Remover dinheiro</option></select></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required/></label><button className="submit">Confirmar</button></form>}
    else if(modal.type==="category"){const c=modal.item;body=<form className="modal" onSubmit={e=>saveCategory(e,c)}><Close/><h2>{c?"Editar":"Nova"} categoria</h2><label>Nome<input name="name" required defaultValue={c?.name}/></label><div className="form-row"><label>Uso<select name="kind" defaultValue={c?.kind??"expense"}><option value="expense">Despesa</option><option value="income">Receita</option><option value="both">Ambos</option></select></label><label>Cor<input name="color" type="color" defaultValue={c?.color??"#f14c8b"}/></label></div><button className="submit">Salvar categoria</button></form>}
    else {const e=modal.item;body=<form className="modal" onSubmit={x=>saveEvent(x,e)}><Close/><h2>{e?"Editar":"Novo"} evento</h2><label>Título<input name="title" required defaultValue={e?.title}/></label><div className="form-row"><label>Data<input name="date" type="date" required defaultValue={e?.date??today()}/></label><label>Valor<input name="amount" type="number" min="0" step="0.01" defaultValue={e?.amount}/></label></div><button className="submit">Salvar evento</button></form>};return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}>{body}</div>}
  function Close(){return <button type="button" className="close" aria-label="Fechar" onClick={()=>setModal(null)}>×</button>}
}
